language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libv8-dev  

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: VH88KqRc9buwU3liODVtnycaBMoqvBrvCPnn3L6ydRALCGKvw4s5NCrb7RSSAnlYJSlTsiw4+fQcbkuhcJJhGUh9wK3avmCh6tJNHOztUxDbkbUzovSgXjCruNogVjnjh06yT/E3UqAINrnA9V1Hp5JUtaG6LzNV2cuP4hyqUfo=
